name: Flask_Deployment
on: 
  push:
    branches: [ main ]
jobs:
  Deplpoy:
    name: Deploy to Ec2
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy into Ec2
      env:
        PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        HOST_NAME: ${{ secrets.HOST_NAME }}
        USER_NAME: ${{ secrets.USER_NAME }}
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER_NAME@$HOST_NAME << 'EOF'
          cd /home/ubuntu/python-flask/
          git pull
          sudo systemctl stop flask-app.service
          sudo systemctl daemon-reload
          sudo systemctl start flask-app.service
        EOF
